<?php

/**
* Instagram downloader class
* Using Curl & Simple HTML DOM
* BY :  Rendrian Gusti Arma
* Website :  https://rendrian.com
*/
class instagramdownload 
{
	
	function __construct()
	{
		include 'simple_html_dom.php';
		# user agent
		$opts = array('http' =>
			array(
				'header'  => 'User-agent: Googlebot/2.1 (http://www.googlebot.com/bot.html)',
			)
		);

		$this->context  = stream_context_create($opts);	}

		function findwonloadlink($instaurl)
		{
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
			//echo $instaurl;
			$ch = curl_init();

			curl_setopt($ch, CURLOPT_URL, trim($instaurl));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

			curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

			$headers = array();
			$headers[] = "Accept-Encoding: gzip, deflate, br";
			$headers[] = "Accept-Language: en-US,en;q=0.8";
			$headers[] = "Upgrade-Insecure-Requests: 1";
			$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36";
			$headers[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8";
			$headers[] = "Cache-Control: max-age=0";
			$headers[] = "Authority: www.instagram.com";
		
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

			$result = curl_exec($ch);
			if (curl_errno($ch)) {
				echo 'Error:' . curl_error($ch);
			}
			curl_close ($ch);
			$dom = new simple_html_dom();

			$data = $dom->load($result);
			$og_title = $data->find('meta[property=og:description]');
			$this->title =  $og_title[0]->{'content'};
			$this->title = explode('Instagram:', $this->title);
			$this->title =  $this->title[1];

			$og_image = $data->find('meta[property=og:image]');
			$this->image =  $og_image[0]->{'content'};
			$og_video = $data->find('meta[property=og:video]');
            $this->video =  $og_video[0]->{'content'}.'<br/>';
            echo json_encode(array(
                "title"=>$this->title,
                "url"=>$this->video
            ),JSON_PRETTY_PRINT);


		}
`

	}

